export const shortlistedTeams = {
    // web: [
    //     "JSM²",
    //     "OrionDevs",
    //     "ErrorHub",
    //     "Sv2s",
    //     "CoreX",
    //     "absolution.",
    //     "Team Σ4i",
    //     "Coding Gurus",
    //     "Quantum Quorum",
    //     "Brocode",
    //     "Team 4i",
    //     "MangoDB",
    //     "Dynamic Duo 101",
    //     "Unite",
    //     "NUCLITRON"
    // ],
    // ai: [
    //     "Low taper fade",
    //     "BinaryBuff",
    //     "Coding Saints",
    //     "AI Annihilators",
    //     "WhyTorch",
    //     "JBBR",
    //     "K_Means_Killers",
    //     "AlgoDevs",
    //     "Debug N Chill",
    //     "India AI",
    //     "TeamnameTBD",
    //     "RCD",
    //     "CodeWithHari",
    //     "KnowWiz",
    //     "Phineas and Ferb"
    // ]
    all: [
        "United 3",
        "Code Valkyries",
        "Hackuna Matata",
        "NeuroNix",
        "CodeDev",
        "TechNites",
        "Code Core",
        "BladeBreakers",
        "Zero",
        "Lazarus",
        "Reactive",
        "Genesis",
        "FlowState",
        "The Solver Squad",
        "Ace of Roots",
        "HackHustlers",
        "The Wingers",
        "Perpendicular",
        "Protocol 7",
        "Caffeine Coders",
        "TrioCoders",
        "Celestial Dragons",
        "Bits&Bytes",
        "404 : Team Not Selected",
        "The Isosceles",
        "Team Crazzy",
        "VectorFlow",
        "Paradigm",
        "ByteBrains",
        "Kakunamatata"
    ]
}